### ISSUE TITLE
 How do I know if I am the first five miners

### ISSUE THREAD

**Issue by huwentao1** [tellor-io/TellorDocumentation#16]
Through the official document, we see that each node can submit prices, but when trb is running for miners, how do I know if I am First five miners, that is to say, how do I know if I have been rewarded, and whether there is any interface to get this information. rpc is available for other currencies, so what about trb

**Comment by themandalore** [comment]
It's a txn on Ethereum, so if it goes through, you'll get a reward.  We would just use the Ethereum RPC (all mining validation happens onchain)
