### ISSUE TITLE
How can I get trb transaction detail info?

### ISSUE THREAD

**Issue by huwentao1** [tellor-io/TellorDocumentation#17]
Hi, I want to get the information in the red box in the picture below. 
Can it be achieved through eth's rpc.
![image](https://user-images.githubusercontent.com/43719888/82795884-3b4f4800-9ea7-11ea-9756-2aaecbe2879c.png)

By the way, are there any documents about how to transfer trb?

**Comment by themandalore** [comment]
yup, and it's just an ERC20 token, so super easy to transfer

**Comment by huwentao1** [comment]
> yup, and it's just an ERC20 token, so super easy to transfer


Hello, can you give an example of how to get the content in the red box according to txid through eth rpc, or is there any document that introduces this, the first time I touched the token, I don’t know how to start. Thank you!
